In [1]:
# Autor: Moisés Martínez
# Correo: moises.martinez@ufv.es
# Título: Example of confidence intervals in simple linear regression.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [2]:
import numpy as np

from scipy.stats import t

In [3]:
# Dataset
x = np.array([2, 3, 5, 7, 8])  # Ages
y = np.array([14, 20, 32, 42, 44])  # Weights

# Global values
n = len(x)
k = 1

In [4]:
coeffients = [0.0 for i in range(k+1)]

# Calculating the means of x and y
x_mean = np.mean(x)
y_mean = np.mean(y)

# Calculating b1
numerator = np.sum((x - x_mean) * (y - y_mean))
denominator = np.sum((x - x_mean)**2)
coeffients[1] = numerator / denominator

# Calculating b0
coeffients[0] = y_mean - coeffients[1] * x_mean

In [5]:
print(f"b1 (slope of the regression line): {coeffients[1]}")
print(f"b0 (y-intercept of the regression line): {coeffients[0]}")

b1 (slope of the regression line): 5.153846153846154
b0 (y-intercept of the regression line): 4.6307692307692285


In [6]:
# Step 1 (Calculation of the residual variance)
y_pred = coeffients[0] + coeffients[1] * x

residuals = y - y_pred

RSS = np.sum(residuals**2)

o_2 = RSS / (n - k - 1)

In [13]:
o_2

np.float64(2.8615384615384536)

In [8]:
# Step 2 (Calculation the Variance-Covariance matrix)
# Matrix X is computed with a column of ones (intercept) and the column of X values

X_matrix = np.vstack([np.ones(len(x)), x]).T

print(X_matrix)

[[1. 2.]
 [1. 3.]
 [1. 5.]
 [1. 7.]
 [1. 8.]]


In [9]:
# Step 2 (Calculation the Variance-Covariance matrix)

XT_X = np.dot(X_matrix.T, X_matrix)

print(XT_X)

[[  5.  25.]
 [ 25. 151.]]


In [ ]:
# Step 2 (Calculation the Variance-Covariance matrix)

XT_X_inv = np.linalg.inv(XT_X)

print(XT_X_inv)

[[ 1.16153846 -0.19230769]
 [-0.19230769  0.03846154]]


In [10]:
# Step 2 (Calculation the Variance-Covariance matrix)

var_cov_matrix = o_2 * XT_X_inv

print(var_cov_matrix)

[[ 3.32378698 -0.55029586]
 [-0.55029586  0.11005917]]


In [11]:
# Step 3 (Calculation the Standard Error (SE))

SEs = []

for coeffienct in range(k + 1):
  SEs.append(np.sqrt(var_cov_matrix[coeffienct, coeffienct]))

print(SEs)

[np.float64(1.823125607918585), np.float64(0.3317516715822737)]


In [12]:
# Computing the degrees of freedom
df = n - k - 1

t_value = t.ppf(
    0.9,
    df)

print(t_value)

confident_intervals = [0.0 for i in range(k+1)]

# Computing the confident intervals for each coefficient
for coeffient in range(k + 1):
  confident_intervals[coeffient] = (
      coeffients[coeffient] - t_value * SEs[coeffient],
      coeffients[coeffient] + t_value * SEs[coeffient])

print(confident_intervals)

1.6377443536962095
[(np.float64(1.6449555603215966), np.float64(7.61658290121686)), (np.float64(4.6105217268830065), np.float64(5.697170580809302))]
